### PR TITLE
fix: entity reduction performance

### LINKED ISSUE #94: Fix: Entity performance
Dealing with a large quantity of entities (7k or more) is considerably slower than `@ngrx/entity` (16.5 sec vs 800ms) when loading into state. Perhaps a less immutable approach would improve performance.

### PR DESCRIPTION
**Pull request by jrista**
* Refactored all Success action entity reductions to use fast mutable approach
 * Added perf testing unit tests to verify that performance meets a generous bar

Resolves #94

### CODE REVIEW

**Comment by jrista** [comment]
Did some basic refactoring of the reducer to use a more performant, mutable approach. The difference in reduction for 10k items loaded with `LoadAll` followed by 10k more items loaded with `LoadMany` (so a total of 20,000 entities) dropped from nearly 20 seconds to about 17 milliseconds:

This was the performance check with the old immutable/spreads approach:

```APL
Expected: < 10
Received:   19425.634977
```

This is the performance check with the new mutable approach:

```APL
Expected: < 10
Received:   16.945756000000074
```

Further testing is probably needed, and I'd like to get some additional unit tests in place, but I think we've achieved more than a reasonable improvement here. For extremely large data sets (hundreds of thousands, millions) this may still not be sufficient, but there may also still be things that could be done to improve performance beyond even this.

**Comment by jrista** [comment]
Test with 100k LoadAll, and 100k more LoadMany:

```APL
Expected: < 10
Received:   48.48160300000018
```

Test with a million each:

```APL
Expected: < 10
Received:   457.2776279999998
```

So even with 2 million entities total, it takes less than half a second to reduce them all in two separate reductions.

**Comment by tonivj5** [comment]
Out of curiosity, if you dont create a new object reference and only mutate it, the selectors should not work (dispatch an update), should?

**Comment by jrista** [comment]
> Out of curiosity, if you dont create a new object reference and only mutate it, the selectors should not work (dispatch an update), should?

So, while I am mutating entities and ids, I am actually copying the root state, and every time the reducer reduces, there is a new copy of state being created. Since every selector starts with getting the root state, and then extracting the given area of state (i.e. customer), which will have changed, I do believe selectors will still update. 

This is something I'm going to test for now, though, to verify.

**Comment by jrista** [comment]
I've done some manual testing, with random updates of a list of entities, with those changed entities being displayed real time through the sorted$ property of the facade (which uses the selectSorted selector). 

As far as I can tell, even though I am mutating the entities and ids properties of the entity state, the whole entity state itself and all of its root properties are being copied, and the selector does appear to work. 

This is still part of the alpha builds for the upcoming v0.5.0 release, though, so further testing will be done before it is actually released to verify that all selectors do indeed work with the new approach to updating state.

It should also be noted that the @ngrx/entity also uses a mutating approach to updating its state, and it (and its selectors) also seem to function properly.

**Pull request merged**
